### ISSUE TITLE
UK store compatibility?

### ISSUE THREAD

**Issue by ak47uk** [EvotecIT/UnifiStockTracker#4]
Thanks for the effort on this, very handy tool, especially as some popular products seem to only be in stock for very short periods. There is now a UK store which uses the new design, is it possible to add compatibility for that too? Thanks

**Comment by PrzemyslawKlys** [comment]
This is now added. Just choose 'UK' and you're done.

**Comment by ak47uk** [comment]
Thanks, I updated to 2.1.0 (I had to remove then reinstall as it complained about publisher) but when running:
`Wait-UnifiStock -ProductSKU 'U6-Lite' -ProductName 'U6 Lite' -Seconds 60 -Store UK`
I get the following:
```
Product Name 'U6 Lite' not found in stock. Ignoring
Product SKU 'U6-Lite' not found in stock. Ignoring
No products requested by user not found on list of available products. Exiting
```
Am I doing something wrong? When I switch UK for Europe then the checker runs every 60 seconds.

**Comment by PrzemyslawKlys** [comment]
You need to use below command to find UK SKU or UK Name to be able to find them properly. I guess each store is different. 

```powershell
Get-UnifiStock -Store UK | Sort-Object -Property Name | Format-Table
```

I believe correct one is:

```powershell
Wait-UnifiStock -ProductSKU 'U6-Lite-US' -Seconds 60 -Store UK
```

**Comment by ak47uk** [comment]
Thanks, the weird thing is on the UK store, the name is "U6 Lite" and the SKU is "U6-Lite". When I use U6-Lite-US, it seems to run the check every 60 secs, as it is out of stock at the moment I can't test if it triggers correctly using that SKU.

**Comment by PrzemyslawKlys** [comment]
Test on a different SKU ;)

**Comment by ak47uk** [comment]
It works for U6-LR which is in stock, but other SKUs that arenot in stock:
```
Wait-UnifiStock -ProductSKU 'UAP-AC-M' -ProductName 'AC Mesh' -Seconds 60 -Store UK
Product Name 'AC Mesh' not found in stock. Ignoring
Product SKU 'UAP-AC-M' not found in stock. Ignoring
No products requested by user not found on list of available products. Exiting
```
The ProductName I am using matches the name in the table when running:
`Get-UnifiStock -Store UK | Sort-Object -Property SKU | Format-Table`

**Comment by PrzemyslawKlys** [comment]
![image](https://github.com/EvotecIT/UnifiStockTracker/assets/15063294/580683f7-a7c6-4551-b03c-ef0b6412bff5)

![image](https://github.com/EvotecIT/UnifiStockTracker/assets/15063294/d7051c41-c82d-4b4b-ae0e-a09a4bf7b096)

![image](https://github.com/EvotecIT/UnifiStockTracker/assets/15063294/34c8bbf8-60fd-47e7-b84f-e0a3014c42eb)

```powershell
Get-UnifiStock -Store UK | Where-Object { $_.SKU -like "*AC*" } | ft Sku, Name
```

The SKU is not there. It seems SKU in UK is weird :)

**Comment by ak47uk** [comment]
That is weird, I ran the same wildcard search for *Lite* and the SKU you had suggested was returned (U6-Lite-US) so I will set up an alert using that and see if it works. Thanks again, I was able to order the U6-Lite form the EU store last week after your script found stock.
