### ISSUE TITLE
One particular item doesn't appear in responses

### ISSUE THREAD

**Issue by LetThatSinkIn** [EvotecIT/UnifiStockTracker#5]
Not sure why, but no matter what I cannot get UACC-CM-RJ45-MG (SFP+ to RJ45 Adapter) to show up in the USA store. Might there be a new collection name that I just can't seem to figure out? It's out of stock at the moment, but I can't see it at all using this.  

I can see what I think is the 1Gbps version of the product 

`SFP to RJ45 Adapter                              SFP to RJ45 Adapter                                   True                                       accessories-pro-sfp-to-rj45-adapter`

But the SFP+ product I mentioned above doesn't appear as either in stock or out of stock.

**Comment by PrzemyslawKlys** [comment]
It's because of the pagination. I'm asking for a maximum of 250 objects in one go, and I forgot to do pagination. Need to add support for it.

**Comment by PrzemyslawKlys** [comment]
It seems to work with newest version

```powershell
$T = Get-UnifiStock -Store USA -Verbose #| Sort-Object -Property Name | Format-Table
$T | Where-Object { $_.SKU -like "*UACC-cm*" } | Format-Table
```

![image](https://github.com/user-attachments/assets/23a9cd6e-edb7-4674-937f-42197f8b61ea)

**Comment by LetThatSinkIn** [comment]
Perfect - working like a charm now!  Thank you!
